services:
  - type: web
    name: concordts-backend
    runtime: python
    buildCommand: |
      pip install --upgrade pip &&
      pip install --only-binary psycopg2-binary -r requirements.txt &&
      python manage.py collectstatic --noinput
    startCommand: gunicorn school_management.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,concordts-backend.onrender.com,localhost,127.0.0.1,yourdomain.com,www.yourdomain.com
      - key: DATABASE_URL
        fromDatabase:
          name: concordts-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://concordts-frontend-9m2hyfafj-femoderalab-3673s-projects.vercel.app,http://localhost:5173,http://localhost:3000,https://yourdomain.com,https://www.yourdomain.com
      - key: CORS_ALLOW_CREDENTIALS
        value: true
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: true
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: ConcordTS <noreply@concordts.com>
      - key: FRONTEND_URL
        value: https://concordts-frontend-9m2hyfafj-femoderalab-3673s-projects.vercel.app
      - key: SCHOOL_NAME
        value: ConcordTS
      - key: SCHOOL_ADDRESS
        value: "NO 31, Adeagbo Yayi Street, Zone 4, Behind Capital Hotel, Osogbo, Nigeria"
      - key: SCHOOL_PHONE
        value: "+2348035312904"

databases:
  - name: concordts-db
    plan: free
    databaseName: school_management_db
    user: school_user